### ISSUE TITLE
Couln't read QR code

### ISSUE THREAD

**Issue by cn-ml** [korki43/gauth-export#1]
What QR code format do you expect? I tried to scan an image i took with a camera, after that i scanned the code using another app and generated a QR code image file and tried to use this but nothing of the above worked. Could you maybe add a function to directly insert the otpauth-migration uri and it decodes it so i don't have the hassle with the QR codes?

Also Google Authenticator disabled the screenshot function so i have to take a photo of the screen anyways

**Comment by kiehnek** [comment]
I'm currently using [`jsQR`](https://github.com/cozmo/jsQR/issues) for the qr code scanning, there are a cases in which a qrcode is (unfortunately) not correctly detected by the library. I'm thinking about switching to the native [`BarCodeDetector`](https://developer.mozilla.org/en-US/docs/Web/API/BarcodeDetector) when more browsers support it. Do you know a better JavaScript (in the best case with TypeScript Definitions) QR-Scanning Library, which is well maintained? When I coded this, jsQR seemed liked the best option but I didn't look to deep into it.

I will add a feature to directly input the otpauth-migration uri. thanks for your feedback!

**Comment by kiehnek** [comment]
Shipped in v2.0.1! I think I will leave the QR code scanning as it is for now. If you think you know another good library for QR scanning, feel free to open a PR. If there's a library which implements scanning and generating of qr codes we would be able to directly generate qr codes for the otp managers. 

Thanks for your feedback! I will close this for now, but if there's more, please comment and i will reopen the issue.

**Comment by cn-ml** [comment]
Unfortunately i have never experimented with qr code scanning before, I cannot help you with that. However i didn't find any other tool to convert my migration uri to otp uris, so thanks for that and the quick reply.
